/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as Super_adminRouteImport } from './routes/_super_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AgendaSlugRouteImport } from './routes/agenda.$slug'
import { Route as Super_adminAdminRouteImport } from './routes/_super_admin/admin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as Super_adminAdminUsuariosRouteImport } from './routes/_super_admin/admin.usuarios'
import { Route as Super_adminAdminRelatoriosRouteImport } from './routes/_super_admin/admin.relatorios'
import { Route as Super_adminAdminDashboardRouteImport } from './routes/_super_admin/admin.dashboard'
import { Route as Super_adminAdminAuditoriaRouteImport } from './routes/_super_admin/admin.auditoria'
import { Route as Super_adminAdminAssinaturasRouteImport } from './routes/_super_admin/admin.assinaturas'
import { Route as AuthenticatedAppServicosRouteImport } from './routes/_authenticated/app.servicos'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppProfissionaisRouteImport } from './routes/_authenticated/app.profissionais'
import { Route as AuthenticatedAppPagamentosRouteImport } from './routes/_authenticated/app.pagamentos'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app.clientes'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp/webhook'
import { Route as ApiPublicMpPlanWebhookRouteImport } from './routes/api/public/mp/plan-webhook'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as ApiPublicCronBillingAlertsRouteImport } from './routes/api/public/cron/billing-alerts'
import { Route as ApiPublicAbacatepayWebhookRouteImport } from './routes/api/public/abacatepay/webhook'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const Super_adminRoute = Super_adminRouteImport.update({
  id: '/_super_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSlugRoute = AgendaSlugRouteImport.update({
  id: '/agenda/$slug',
  path: '/agenda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Super_adminAdminRoute = Super_adminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => Super_adminRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const Super_adminAdminUsuariosRoute =
  Super_adminAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => Super_adminAdminRoute,
  } as any)
const Super_adminAdminRelatoriosRoute =
  Super_adminAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => Super_adminAdminRoute,
  } as any)
const Super_adminAdminDashboardRoute =
  Super_adminAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Super_adminAdminRoute,
  } as any)
const Super_adminAdminAuditoriaRoute =
  Super_adminAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => Super_adminAdminRoute,
  } as any)
const Super_adminAdminAssinaturasRoute =
  Super_adminAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => Super_adminAdminRoute,
  } as any)
const AuthenticatedAppServicosRoute =
  AuthenticatedAppServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfissionaisRoute =
  AuthenticatedAppProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPagamentosRoute =
  AuthenticatedAppPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpPlanWebhookRoute = ApiPublicMpPlanWebhookRouteImport.update({
  id: '/api/public/mp/plan-webhook',
  path: '/api/public/mp/plan-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronBillingAlertsRoute =
  ApiPublicCronBillingAlertsRouteImport.update({
    id: '/api/public/cron/billing-alerts',
    path: '/api/public/cron/billing-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAbacatepayWebhookRoute =
  ApiPublicAbacatepayWebhookRouteImport.update({
    id: '/api/public/abacatepay/webhook',
    path: '/api/public/abacatepay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin': typeof Super_adminAdminRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/admin/assinaturas': typeof Super_adminAdminAssinaturasRoute
  '/admin/auditoria': typeof Super_adminAdminAuditoriaRoute
  '/admin/dashboard': typeof Super_adminAdminDashboardRoute
  '/admin/relatorios': typeof Super_adminAdminRelatoriosRoute
  '/admin/usuarios': typeof Super_adminAdminUsuariosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/abacatepay/webhook': typeof ApiPublicAbacatepayWebhookRoute
  '/api/public/cron/billing-alerts': typeof ApiPublicCronBillingAlertsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/mp/plan-webhook': typeof ApiPublicMpPlanWebhookRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin': typeof Super_adminAdminRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/admin/assinaturas': typeof Super_adminAdminAssinaturasRoute
  '/admin/auditoria': typeof Super_adminAdminAuditoriaRoute
  '/admin/dashboard': typeof Super_adminAdminDashboardRoute
  '/admin/relatorios': typeof Super_adminAdminRelatoriosRoute
  '/admin/usuarios': typeof Super_adminAdminUsuariosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/abacatepay/webhook': typeof ApiPublicAbacatepayWebhookRoute
  '/api/public/cron/billing-alerts': typeof ApiPublicCronBillingAlertsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/mp/plan-webhook': typeof ApiPublicMpPlanWebhookRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_super_admin': typeof Super_adminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_super_admin/admin': typeof Super_adminAdminRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/_authenticated/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/servicos': typeof AuthenticatedAppServicosRoute
  '/_super_admin/admin/assinaturas': typeof Super_adminAdminAssinaturasRoute
  '/_super_admin/admin/auditoria': typeof Super_adminAdminAuditoriaRoute
  '/_super_admin/admin/dashboard': typeof Super_adminAdminDashboardRoute
  '/_super_admin/admin/relatorios': typeof Super_adminAdminRelatoriosRoute
  '/_super_admin/admin/usuarios': typeof Super_adminAdminUsuariosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/abacatepay/webhook': typeof ApiPublicAbacatepayWebhookRoute
  '/api/public/cron/billing-alerts': typeof ApiPublicCronBillingAlertsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/mp/plan-webhook': typeof ApiPublicMpPlanWebhookRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/app'
    | '/onboarding'
    | '/admin'
    | '/agenda/$slug'
    | '/auth/callback'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/pagamentos'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/servicos'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/dashboard'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/app/'
    | '/api/public/abacatepay/webhook'
    | '/api/public/cron/billing-alerts'
    | '/api/public/google/callback'
    | '/api/public/mp/plan-webhook'
    | '/api/public/mp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/onboarding'
    | '/admin'
    | '/agenda/$slug'
    | '/auth/callback'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/pagamentos'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/servicos'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/dashboard'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/app'
    | '/api/public/abacatepay/webhook'
    | '/api/public/cron/billing-alerts'
    | '/api/public/google/callback'
    | '/api/public/mp/plan-webhook'
    | '/api/public/mp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_super_admin'
    | '/cadastro'
    | '/entrar'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_super_admin/admin'
    | '/agenda/$slug'
    | '/auth/callback'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/pagamentos'
    | '/_authenticated/app/profissionais'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/servicos'
    | '/_super_admin/admin/assinaturas'
    | '/_super_admin/admin/auditoria'
    | '/_super_admin/admin/dashboard'
    | '/_super_admin/admin/relatorios'
    | '/_super_admin/admin/usuarios'
    | '/_authenticated/app/'
    | '/api/public/abacatepay/webhook'
    | '/api/public/cron/billing-alerts'
    | '/api/public/google/callback'
    | '/api/public/mp/plan-webhook'
    | '/api/public/mp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  Super_adminRoute: typeof Super_adminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  AgendaSlugRoute: typeof AgendaSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicAbacatepayWebhookRoute: typeof ApiPublicAbacatepayWebhookRoute
  ApiPublicCronBillingAlertsRoute: typeof ApiPublicCronBillingAlertsRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicMpPlanWebhookRoute: typeof ApiPublicMpPlanWebhookRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super_admin': {
      id: '/_super_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Super_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$slug': {
      id: '/agenda/$slug'
      path: '/agenda/$slug'
      fullPath: '/agenda/$slug'
      preLoaderRoute: typeof AgendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super_admin/admin': {
      id: '/_super_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Super_adminAdminRouteImport
      parentRoute: typeof Super_adminRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_super_admin/admin/usuarios': {
      id: '/_super_admin/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof Super_adminAdminUsuariosRouteImport
      parentRoute: typeof Super_adminAdminRoute
    }
    '/_super_admin/admin/relatorios': {
      id: '/_super_admin/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof Super_adminAdminRelatoriosRouteImport
      parentRoute: typeof Super_adminAdminRoute
    }
    '/_super_admin/admin/dashboard': {
      id: '/_super_admin/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof Super_adminAdminDashboardRouteImport
      parentRoute: typeof Super_adminAdminRoute
    }
    '/_super_admin/admin/auditoria': {
      id: '/_super_admin/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof Super_adminAdminAuditoriaRouteImport
      parentRoute: typeof Super_adminAdminRoute
    }
    '/_super_admin/admin/assinaturas': {
      id: '/_super_admin/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof Super_adminAdminAssinaturasRouteImport
      parentRoute: typeof Super_adminAdminRoute
    }
    '/_authenticated/app/servicos': {
      id: '/_authenticated/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AuthenticatedAppServicosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profissionais': {
      id: '/_authenticated/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AuthenticatedAppProfissionaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pagamentos': {
      id: '/_authenticated/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AuthenticatedAppPagamentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/plan-webhook': {
      id: '/api/public/mp/plan-webhook'
      path: '/api/public/mp/plan-webhook'
      fullPath: '/api/public/mp/plan-webhook'
      preLoaderRoute: typeof ApiPublicMpPlanWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/billing-alerts': {
      id: '/api/public/cron/billing-alerts'
      path: '/api/public/cron/billing-alerts'
      fullPath: '/api/public/cron/billing-alerts'
      preLoaderRoute: typeof ApiPublicCronBillingAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/abacatepay/webhook': {
      id: '/api/public/abacatepay/webhook'
      path: '/api/public/abacatepay/webhook'
      fullPath: '/api/public/abacatepay/webhook'
      preLoaderRoute: typeof ApiPublicAbacatepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppPagamentosRoute: typeof AuthenticatedAppPagamentosRoute
  AuthenticatedAppProfissionaisRoute: typeof AuthenticatedAppProfissionaisRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppServicosRoute: typeof AuthenticatedAppServicosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppPagamentosRoute: AuthenticatedAppPagamentosRoute,
  AuthenticatedAppProfissionaisRoute: AuthenticatedAppProfissionaisRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppServicosRoute: AuthenticatedAppServicosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface Super_adminAdminRouteChildren {
  Super_adminAdminAssinaturasRoute: typeof Super_adminAdminAssinaturasRoute
  Super_adminAdminAuditoriaRoute: typeof Super_adminAdminAuditoriaRoute
  Super_adminAdminDashboardRoute: typeof Super_adminAdminDashboardRoute
  Super_adminAdminRelatoriosRoute: typeof Super_adminAdminRelatoriosRoute
  Super_adminAdminUsuariosRoute: typeof Super_adminAdminUsuariosRoute
}

const Super_adminAdminRouteChildren: Super_adminAdminRouteChildren = {
  Super_adminAdminAssinaturasRoute: Super_adminAdminAssinaturasRoute,
  Super_adminAdminAuditoriaRoute: Super_adminAdminAuditoriaRoute,
  Super_adminAdminDashboardRoute: Super_adminAdminDashboardRoute,
  Super_adminAdminRelatoriosRoute: Super_adminAdminRelatoriosRoute,
  Super_adminAdminUsuariosRoute: Super_adminAdminUsuariosRoute,
}

const Super_adminAdminRouteWithChildren =
  Super_adminAdminRoute._addFileChildren(Super_adminAdminRouteChildren)

interface Super_adminRouteChildren {
  Super_adminAdminRoute: typeof Super_adminAdminRouteWithChildren
}

const Super_adminRouteChildren: Super_adminRouteChildren = {
  Super_adminAdminRoute: Super_adminAdminRouteWithChildren,
}

const Super_adminRouteWithChildren = Super_adminRoute._addFileChildren(
  Super_adminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  Super_adminRoute: Super_adminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  AgendaSlugRoute: AgendaSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicAbacatepayWebhookRoute: ApiPublicAbacatepayWebhookRoute,
  ApiPublicCronBillingAlertsRoute: ApiPublicCronBillingAlertsRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicMpPlanWebhookRoute: ApiPublicMpPlanWebhookRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
